### PR TITLE
Generate GIFs with different board themes and piece sets

### PR DESCRIPTION
**Pull request by brollin**
> For sanity's sake, I recommend reviewing commit by commit!

This addresses https://github.com/lichess-org/lila/issues/11308. We generate sprites for many combinations of board theme and piece set. Then we use the appropriate sprite when generating an image or animation from a theme map.

I learned Rust from scratch over the course of doing this task, so there may be some glaring no-nos... But hopefully not!

### CODE REVIEW

**Comment by brollin** [comment]
Okay, @niklasf, this is ready for a look! It's not a huge change all in all, despite the file/LOC diff. cc @ornicar

**Comment by brollin** [comment]
image

A taste of what's ahead! :)

**Comment by niklasf** [comment]
Thanks! Very cool! Deployed.

I changed the initialization a bit to simplify deployment. Everything in one binary at the cost of a silly [list of files](https://github.com/lichess-org/lila-gif/blob/0d8875cbc10b0e5feba5622528dffbc2b3c2b70e/src/assets.rs#L128-L286).

**Comment by niklasf** [comment]
Btw. no worries about `mono`. It's used to visualize the material difference, so never on the board.

**Comment by niklasf** [comment]
For some reason the images and animations rendered with latest master appear completely white in my Chrome 104. Currently at the airport, returning from the meetup, running out of battery, so reverted in prod for now.

**Comment by brollin** [comment]
So strange! Yeah, I'm seeing the issue too. Images seem to work on Chrome 104, but not games as you say.

My best hunch is that it is some `gift` encoding issue. Incidentally, my roommate (@milotoor) is getting into Rust and just finished refactoring `lila-gif` to use `gif` instead of `gift`. Locally, I was able to verify that with his changes, games on chrome do display correctly.

What do you think about switching from `gift` to `gif`? I noticed you have a history of helping out with `gift`, but it seems over the last two years `gif` has become the defacto gif library, so it might be nice longer term.

**Comment by niklasf** [comment]
I like that `gift` can easily start sending frames before rendering is complete. Maybe `gif` can do the same? In any case, I am not opposed to switching.

**Comment by brollin** [comment]
Makes sense that that would be a requirement for switching, since I think the UX would suffer greatly otherwise. I believe there is a way to do that with `gif`, but I will double check with Milo.

**Comment by brollin** [comment]
Ok, just an quickupdate. I've only looked into it a little bit, and so far not understanding the problem with my changes that break game gifs for chrome. Milo has been working here https://github.com/milotoor/lila-gif/tree/gif-for-gift and found that the LZW compression is far slower in `gif` for some reason. When run in release mode, it's 3x slower or worse.

I will keep looking into what's wrong with my changes. Hopefully I stumble upon a solution soon. 🤞

**Comment by brollin** [comment]
Hey @niklasf, not sure if you saw it yet but the above PR #116 solves this problem, at the cost of being a little slower. Curious if you're okay with that tradeoff?

**Pull request merged**
